### ISSUE TITLE
missing include <optional>

### ISSUE THREAD

**Issue by lancos** [Simsys/qhexedit2#155]
Build on Linux (Ubuntu24.04) fails with this error:

```
../example/main.cpp:24:10: error: ‘optional’ in namespace ‘std’ does not name a template type
   24 |     std::optional<QString> errorString = std::nullopt;
      |          ^~~~~~~~
../example/main.cpp:9:1: note: ‘std::optional’ is defined in header ‘<optional>’; did you forget to ‘#include <optional>’?
    8 | #include "mainwindow.h"
  +++ |+#include <optional>
    9 | 

```

Add #include \<optional\> fix it.
